# Site settings
title: fatemekazemi | فاطمه کاظمی
email: hi@fatemekazemi.ir
description: دانشجوی مهندسی کامپیوتر نرم افزار
baseurl: "http://fatemekazemi.ir/"
url: "http://fatemekazemi.ir"
twitter: _kazemii
github:  fatemekazemi
behance: fatemekazemi
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]